### PR TITLE
Fix useNativeDriver warnings

### LINKED ISSUE #2464: Refractor: Fix all animated useNativeDriver warnings
better to replace Animated with reanimated package.
with reanimated add easeinout property

### PR DESCRIPTION
**Pull request by aliseyalvi**
### What does this PR?
This PR is WIP for removing/fixing useNativeDriver warnings to either set useNativeDriver to true or replace with React Native Reanimated component
 
### Issue number
fixes #2464

### CODE REVIEW

**Comment by aliseyalvi** [comment]
@noumantahir tried to find the useNativeDriver warnings, let me know if I had missed any or find any other warning relared to useNativeDriver

File: src/components/collapsibleCard/view/collapsibleCardView.js [hunk 1]
```diff
@@ -50,6 +50,7 @@ class CollapsibleCardView extends PureComponent {
     Animated.timing(this.anime.height, {
       toValue: this.anime.expanded ? this._getMinValue() : this._getMaxValue() + (moreHeight || 0),
       duration: 200,
+      useNativeDriver: false,
```
Comment (noumantahir) [inline src/components/collapsibleCard/view/collapsibleCardView.js:53]: using native driver as false means js thread will be handling the animation. can you please try replacing Animated package with `react-native-reanimated` as we discussed. Start with this one and better replace the package in all places.

**Review by noumantahir — CHANGES_REQUESTED** [review]
The priority is to replace all `import {Animated} from react-native ` with `import Animated, { Easing, Extrapolate } from 'react-native-reanimated';`

If for some reason some implementation of Animated become complicated to migrate to reanimated package, only then set `useNativeDriver` to true. And we should only allow `useNativeDriver` as false if we are out of options completely.

File: src/components/collapsibleCard/view/collapsibleCardView.js (hunk 1 above)
Comment (aliseyalvi) [reply src/components/collapsibleCard/view/collapsibleCardView.js:53]: @noumantahir height property is not supported animation on native thread. Tried to find a solution, one solution which I found is to replace height with scaling because scaling supports native animation. I can give that a try again

Comment (aliseyalvi) [reply src/components/collapsibleCard/view/collapsibleCardView.js]: replaced with react-native-reanimated

**Comment by aliseyalvi** [comment]
@noumantahir replaced occurences of Animated from react-native with Animated from react-native-reanimated. ProgressiveImage component is left with native Animated as it is not being reused.

**Review by noumantahir — CHANGES_REQUESTED** [review]
Two issue detected... 

1. App crashes when entering pin code.
Screenshot 2022-09-29 at 2 31 22 PM

2. toast notification opacity is never reaching full opacity, while it is working fine in current development.
Screenshot 2022-09-29 at 2 39 36 PM

Both of these animations can even be changed to use `react-native-reanimatable` instead of reanimated package for simplified and clean code implementation. do whatever seems like a goto solution

**Comment by aliseyalvi** [comment]
@noumantahir replaced reanimated in pinAnimatedInput with animatable and toastNotification as well

File: src/components/pinAnimatedInput/views/pinAnimatedInputView.js [hunk 2]
```diff
@@ -1,7 +1,7 @@
 /* eslint-disable react/no-array-index-key */
 import React, { Component } from 'react';
 import { View } from 'react-native';
-import Animated, { Easing } from 'react-native-reanimated';
+import * as Animatable from 'react-native-animatable';
```
Comment (noumantahir) [inline src/components/pinAnimatedInput/views/pinAnimatedInputView.js:4]: better use `import { View as AnimatableView } from 'react-native-animatable'` import * .... is almost always very expensive import

File: src/components/toastNotification/view/toastNotificaitonView.js [hunk 3]
```diff
@@ -1,6 +1,6 @@
 import React, { Component } from 'react';
 import { TouchableOpacity, Text } from 'react-native';
-import Animated, { Easing } from 'react-native-reanimated';
+import * as Animatable from 'react-native-animatable';
```
Comment (noumantahir) [inline src/components/toastNotification/view/toastNotificaitonView.js:3]: better use import { View as AnimatableView } from 'react-native-animatable' import * .... is almost always very expensive import

Comment (aliseyalvi) [reply src/components/toastNotification/view/toastNotificaitonView.js:3]: Ok

**Review by noumantahir — CHANGES_REQUESTED** [review]
- toastNotification is working great now. do check one change request I placed
- revert pinAnimatedInput to previous behaviour (before this branch), it was a very refined animation compared to simple fading

**Comment by aliseyalvi** [comment]
@noumantahir reverted changes in pinAnimatedInput

**Review by noumantahir — APPROVED** [review]
lgtm

**Review by feruzm — APPROVED** [review]
