### PR TITLE
Nt/tweaks

### LINKED ISSUE #1867: Favourites album unavailable while picking images on iOS
Another report if you can take a look, user reporting they cannot see images from their favorites list or album, when upload

**Screenshot**
https://cdn.discordapp.com/attachments/808287446948249632/822874474105405491/image0.png

### LINKED ISSUE #1868: Profile cover image not expanding to full width
Another bug: profile cover image style has changed for some reason not full width

**To Reproduce**
1. Go to Profile screen for @ecency as sample

**Expected behavior**
Cover photo should cover all width

**Screenshots**
779495CB-0C83-49CB-894C-B3152FBCDBE1

### LINKED ISSUE #1870: Posts scrolling glitch, momentary image flash
**Describe the bug**
While scrolling posts lists a glitch is experienced sometimes... it appears as if the image sometimes covers the whole screen momentary before settling actual height... only happens to some posts

**To Reproduce**
2. Steps to reproduce the behavior:

**Expected behavior**
Scroll should appear as smooth as possible

**Screenshots or Video**
https://user-images.githubusercontent.com/6298342/111971695-6bdf2d00-8b1e-11eb-97bd-ee1eac846c6f.MP4

**Smartphone (please complete the following information):**
 - Device:  [iPhone11]
 - Ecency v3.0.15 (2927)

### LINKED ISSUE #1873: Replace postcard touchable opacity with no feedback touchable
Every once in a while when scroll while tapping directly on a post image, it creates a flashy effect of changing view opacity and then discard the touch event in favour of scroll, this creates a somewhat annoying experience for user..

tapping on a post image to open detail is more or less a second nature for a regular social media consumer, I would say it safe make the tap with giving feedback to user... even facebook do use no tap feedback approach.

Steps to reproduce the behaviour:
1. Go to feed
2. Tap down on post image 
3. Start scrolling without lifting your finger
4. You will experience a flashy effect before scroll

**Screenshots or Video**

https://user-images.githubusercontent.com/6298342/112035626-8d153d00-8b61-11eb-882a-d32e5d49c6a1.mov

### PR DESCRIPTION
**Pull request by noumantahir**
### What does this PR?
- fixed banner not appearing and appearing to be small in profile screen
- added favourites section in iOS image picker, removed videos,
- fixed iOS scrolling glitch by maintain height cache outside post card.

### Where should the reviewer start?
- profile screen
- image picker while creating new posts
- scrolling feeds back and forth

### Issue number
fixes #1867
fixes #1868
fixes #1870
fixes #1873

### CODE REVIEW

File: src/utils/postParser.js [hunk 1]
```diff
@@ -24,6 +25,9 @@ export const parsePost = (post, currentUserName, isPromoted, isList = false) =>
   if (!post) {
     return null;
   }
+
+  post.local_id = generateUuid({ short: true });
```
Comment (feruzm) [inline src/utils/postParser.js:29]: Instead of creating uuid, we can utilize author + permlink as key for ensured uniqueness of each post.

Comment (noumantahir) [reply src/utils/postParser.js:29]: discarded generateUUid in favour of author permlink mix

**Comment by noumantahir** [comment]
- now fetching 20 posts for feed and 5 posts as refresh check
- discarded generate uuid

File: src/components/postsList/container/postsListContainer.tsx [hunk 2]
```diff
@@ -56,29 +58,50 @@ const postsListContainer = ({
       
     }, [scrollPosition])
 
+
+    const _setImageHeightInMap = (postId:number, height:number) => {
```
Comment (feruzm) [inline src/components/postsList/container/postsListContainer.tsx:62]: shouldn't postId be `string` now?

File: src/screens/editor/container/editorContainer.js [hunk 3]
```diff
@@ -101,6 +101,7 @@ class EditorContainer extends Component {
     ImagePicker.openPicker({
       includeBase64: true,
       multiple: true,
+      smartAlbums: ['UserLibrary', 'Favorites', 'PhotoStream', 'Panoramas', 'Bursts'],
```
Comment (feruzm) [inline src/screens/editor/container/editorContainer.js:104]: We should probably add `mediaType: 'photo'`
`mediaType | string (default any) | Accepted mediaType for image selection, can be one of: 'photo', 'video', or 'any'`

Comment (noumantahir) [reply src/screens/editor/container/editorContainer.js:104]: agreed: because smartAlbums list only works for iOS... mediaType will cover android too

File: src/components/postsList/container/postsListContainer.tsx (hunk 2 above)
Comment (noumantahir) [reply src/components/postsList/container/postsListContainer.tsx:62]: agreed, it should have been string before as well.. thanks

**Review by feruzm — APPROVED** [review]
lgtm, let's do some tests on device
