### PR TITLE
Nt/experiment feed stability

### LINKED ISSUE #2618: Attempt to fix iOS crash while exploring app..
**Checklist**

- [x] avoid using navigation hook in postHeaderDescription
- [x] Cleanly implement single upvote popover handler
- [x] create single post options dropdown outside of flatlist
- [x] avoid using navigation hook in post card actions
- [x] handle reblogs fetch
- [x] optimise promoted posts injection
- [x] remove new posts check for now
- [x] update rest of Upvote implementations
- [x] handle upvote cache
- [x] handle post dropdown in post screen
- [x] fix post options modal response on android
- [x] move video player out of comment body
- [x] move options modal out of comment body, imageAction linkAction, youtubePlayer, imageViewer
- [x] move delete options modal out of comment item render

**_Archived_**
_During my testing I am able to narrow it down to primary Friends feed screen. some times app would crash on opening a post, or one time it even crash just preforming simple ScrollToTop operation, the time to crash is also not consistent..

there is only one such random operation that might lead to crash and that would be ..

_scheduleLatestPostsCheck() firing at random intervals
usage of setTimout might also be the reason for crashing as scrollToTop also use it just like scheduleLatestPostCheck()

Make sure timeouts are small and are cleared even if they have been executed_

### PR DESCRIPTION
**Pull request by noumantahir**
### What does this PR?
Relatively large PR attempts to refactor and optimise the feed exploration and post details screens. Post Card actions votes, dropdown etc and Comment list actions including comment html/markdown actions need to be tested thoroughly.

**Checklist**

- [x] avoid using navigation hook in postHeaderDescription
- [x] Cleanly implement single upvote popover handler
- [x] create single post options dropdown outside of flatlist
- [x] avoid using navigation hook in post card actions
- [x] handle reblogs fetch
- [x] optimise promoted posts injection
- [x] remove new posts check for now
- [x] update rest of Upvote implementations
- [x] handle upvote cache
- [x] handle post dropdown in post screen
- [x] fix post options modal response on android
- [x] move video player out of comment body
- [x] move options modal out of comment body, imageAction linkAction, youtubePlayer, imageViewer
- [x] move delete options modal out of comment item render
- [x] update post screen after post content update

### Where should the reviewer start?
Feed Scrolling, Post card interactions, Post details screen interactions

### Issue number
fixes #2618 

### Screenshots/Video
Final user interface is mostly kept the same, primary UI change includes a new post dropdown modal, that is now a single action sheet shared among all posts in feed list.

Screenshot 2023-03-01 at 12 46 34 PM
Screenshot 2023-03-01 at 12 46 14 PM

### CODE REVIEW

File: src/components/autoHeightImage/autoHeightImage.tsx [hunk 1]
```diff
@@ -1,8 +1,8 @@
 import React, { useEffect, useState } from 'react';
-import { Image } from 'react-native';
+import { Image, TouchableOpacity } from 'react-native';
 import EStyleSheet from 'react-native-extended-stylesheet';
 import FastImage from 'react-native-fast-image';
-import { TouchableOpacity } from 'react-native-gesture-handler';
```
Comment (feruzm) [inline src/components/autoHeightImage/autoHeightImage.tsx:5]: @noumantahir RN touchableopacity had some issues that's why we were using another package, did you check if it doesn't break anything?

File: src/components/autoHeightImage/autoHeightImage.tsx [hunk 2]
```diff
@@ -39,11 +39,12 @@ export const AutoHeightImage = ({
   const imgStyle = {
     width: imgWidth - 10,
     height: imgHeight,
-    backgroundColor: onLoadCalled ? 'transparent' : EStyleSheet.value('$primaryGray'),
+    backgroundColor: onLoadCalled ? 'transparent' : EStyleSheet.value('$primaryLightBackground'),
```
Comment (feruzm) [inline src/components/autoHeightImage/autoHeightImage.tsx:42]: We have added image ratio on website, should consider adding that into mobile app as well and also start utilizing those ratio information.

File: src/components/postCard/children/upvoteButton.tsx [hunk 3]
```diff
@@ -0,0 +1,160 @@
...
+        <View style={styles.container}>
+            <TouchableOpacity
+                ref={upvoteRef}
+                onPress={_onPress}
+                style={styles.upvoteButton}
+            >
+                <Fragment>
+                    {isVoting ? (
+                        <View style={{ width: 19 }}>
+                            <PulseAnimation
```
Comment (feruzm) [inline src/components/postCard/children/upvoteButton.tsx:120]: We added new animation to heart icon after vote is cast we animated heart as well on website. Good to have it on app as well, in separate task of course, just mentioning so we don't forget. Check it out please!

File: src/components/postComments/container/postComments.tsx [hunk 4]
```diff
@@ -106,7 +119,7 @@ const PostComments = forwardRef(
           content,
         },
         key: content.permlink,
-      });
+      } as never);
```
Comment (feruzm) [inline src/components/postComments/container/postComments.tsx:122]: what's the benefit of `as never`, haven't seen or used this before personally, just curious.

File: src/components/postComments/container/postComments.tsx [hunk 5]
```diff
@@ -242,132 +284,53 @@ const PostComments = forwardRef(
           index={index}
           mainAuthor={mainAuthor}
           handleDeleteComment={_handleDeleteComment}
-          handleOnEditPress={_handleOnEditPress}
+          handleOnEditPress={_handleOnEditPress}s
```
Comment (feruzm) [inline src/components/postComments/container/postComments.tsx:287]: after bracket there is typo `s`

File: src/components/postHtmlRenderer/videoThumb.tsx [hunk 6]
```diff
@@ -1,7 +1,6 @@
 import React from 'react';
-import { View, ImageBackground } from 'react-native';
+import { View, ImageBackground, TouchableHighlight } from 'react-native';
```
Comment (feruzm) [inline src/components/postHtmlRenderer/videoThumb.tsx:2]: also here about TouchableHighlight, if we using RN and it is working ok, we should consider removing `react-native-gesture-handler` package.

File: src/screens/searchResult/screen/tabs/best/view/postsResults.js [hunk 7]
```diff
@@ -35,6 +35,7 @@ const PostsResults = ({ navigation, searchValue }) => {
           reputation={Math.floor(reputation)}
           size={36}
           content={item}
+          profileOnPress={()=> {}} //TODO: handle on user press before PR
```
Comment (feruzm) [inline src/screens/searchResult/screen/tabs/best/view/postsResults.js:38]: TODO remaining?

**Review by feruzm — CHANGES_REQUESTED** [review]

File: src/components/autoHeightImage/autoHeightImage.tsx (hunk 1 above)
Comment (noumantahir) [reply src/components/autoHeightImage/autoHeightImage.tsx:5]: at this point, I am undecided, because both show issues in different aspects... on android gesture-handler touchable stopped responding in recent updates, reported by melinda as well.... that is why shifted back to stock touchable.

File: src/components/postComments/container/postComments.tsx (hunk 4 above)
Comment (noumantahir) [reply src/components/postComments/container/postComments.tsx:122]: it is not the right way to use never, never essentially points towards a no return type...here however using it temporarily to remove ugly red lines from code, right way would be to cast every `useNavigation()` with right type.

File: src/components/postCard/children/upvoteButton.tsx (hunk 3 above)
Comment (noumantahir) [reply src/components/postCard/children/upvoteButton.tsx:123]: I rather removed pulse animation in latest code in favour of using PENDING voting state in cache, will check out heart animation as well, adding that as separate task in backlog

File: src/components/postCard/children/upvoteButton.tsx [hunk 8]
```diff
@@ -0,0 +1,160 @@
...
+
+    const [isVoted, setIsVoted] = useState(null);
+    const [isDownVoted, setIsDownVoted] = useState(null);
+
+
+
+    useEffect(() => {
+        let _isMounted = true;
+
+        const _calculateVoteStatus = async () => {
```
[the remark this answers is not in the document]
Comment (noumantahir) [reply src/components/postCard/children/upvoteButton.tsx]: this is already resolved, also improved using `useCallback`

File: src/components/autoHeightImage/autoHeightImage.tsx (hunk 2 above)
Comment (noumantahir) [reply src/components/autoHeightImage/autoHeightImage.tsx:42]: adding to backlog

File: src/components/postCard/children/upvoteButton.tsx (hunk 3 above)
Comment (feruzm) [reply src/components/postCard/children/upvoteButton.tsx:123]: We did keep pulse animation on vote button and added new animation to heart icon (number of votes) icon. That's extra animation. Removing pulse now is not required, imo.

File: src/components/postComments/container/postComments.tsx (hunk 5 above)
Comment (feruzm) [reply src/components/postComments/container/postComments.tsx:287]: @noumantahir didn't check this typo, it was intentional maybe?

**Review by feruzm — APPROVED** [review]
Lgtm, let’s do more tests
